name: Docker

on:
  push:
    branches: [ main ]
    tags:     [ "v*.*.*" ]
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/hello-java

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write    # needed to push to GHCR

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Compute tags
        id: meta
        run: |
          SHA_TAG="sha-${GITHUB_SHA::7}"
          echo "sha_tag=${SHA_TAG}" >> $GITHUB_OUTPUT
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            echo "ref_tag=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          fi

      - name: Build & push (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.sha_tag }}
            ${{ steps.meta.outputs.ref_tag && format('{0}:{1}', env.IMAGE_NAME, steps.meta.outputs.ref_tag) || '' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
